node_js:
  - "12.14"

language: node_js

dist: trusty

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install -g @angular/cli
  - npm install

script:
  - npm run test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox