node_js:
  - "12.14"

language: node_js

addons:
  apt: 
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - npm install -g @angular/cli
  - npm install

script:
  - npm run test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox